//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_Types
    {
        public Equipment_Types()
        {
            this.Instrument_Equipment_Details = new HashSet<Instrument_Equipment_Details>();
        }
    
        public int id { get; set; }
        public int Purchase_Category_Id { get; set; }
        public string Equipment_Type { get; set; }
    
        public virtual Purchase_Categories Purchase_Categories { get; set; }
        public virtual ICollection<Instrument_Equipment_Details> Instrument_Equipment_Details { get; set; }
    }
}
