//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Industry_Details
    {
        public Industry_Details()
        {
            this.PO_Details = new HashSet<PO_Details>();
        }
    
        public int id { get; set; }
        public string Industry_FullName { get; set; }
        public string Industry_ShortName { get; set; }
        public string Industry_Code { get; set; }
        public Nullable<int> Industry_TypeID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Email_ID { get; set; }
        public string ContactNumber { get; set; }
    
        public virtual Industry_Types Industry_Types { get; set; }
        public virtual ICollection<PO_Details> PO_Details { get; set; }
    }
}
