//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Industry_Types
    {
        public Industry_Types()
        {
            this.Industry_Details = new HashSet<Industry_Details>();
        }
    
        public int id { get; set; }
        public string IndustryType { get; set; }
    
        public virtual ICollection<Industry_Details> Industry_Details { get; set; }
    }
}
