//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Categories
    {
        public Purchase_Categories()
        {
            this.PO_Details = new HashSet<PO_Details>();
        }
    
        public int id { get; set; }
        public string purchase_categorytype { get; set; }
    
        public virtual ICollection<PO_Details> PO_Details { get; set; }
    }
}
