//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public state()
        {
            this.districts = new HashSet<district>();
        }
    
        public int id { get; set; }
        public string state1 { get; set; }
    
        public virtual ICollection<district> districts { get; set; }
    }
}
